# dbt_project.yml
# Este arquivo define configurações do projeto dbt, incluindo caminhos, nome e versão.

name: 'dbt_analytics'
version: '1.0'
config-version: 2

profile: 'default'  # Nome que será usado no profiles.yml para conectar com o BQ

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  dbt_analytics:
    +materialized: table  # padrão para os modelos se não for especificado individualmente
